;;; dired-preview-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dired-preview.el

(autoload 'dired-preview-mode "dired-preview" "\
Buffer-local mode to preview file at point in Dired.

This is a minor mode.  If called interactively, toggle the
`Dired-Preview mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `dired-preview-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'dired-preview-global-mode 'globalized-minor-mode t)
(defvar dired-preview-global-mode nil "\
Non-nil if Dired-Preview-Global mode is enabled.
See the `dired-preview-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `dired-preview-global-mode'.")
(custom-autoload 'dired-preview-global-mode "dired-preview" nil)
(autoload 'dired-preview-global-mode "dired-preview" "\
Toggle Dired-Preview mode in all buffers.
With prefix ARG, enable Dired-Preview-Global mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Dired-Preview mode is enabled in all buffers where `dired-preview--on' would do
it.

See `dired-preview-mode' for more information on Dired-Preview mode.

(fn &optional ARG)" t)
(register-definition-prefixes "dired-preview" '("dired-preview-"))

;;; End of scraped data

(provide 'dired-preview-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dired-preview-autoloads.el ends here
